name = "nautica"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
PRX_BANK_URL = "https://raw.githubusercontent.com/bitscoid/BITS-Cloudflare-VPN/main/proxyList.txt"
# Aktifkan jika kamu punya converter sendiri (untuk format sfa/bfr/clash):
# CONVERTER_URL = "https://converter.example.com/convert"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
