// Constants from worker.js (lines 1-45 + helpers)

export const neko = 'dmxlc3M=';
export const v2 = 'djJyYXk=';

export const PROTOCOLS = [atob(neko)];
export const KV_PRX_URL =
  'https://raw.githubusercontent.com/Banten-IT-Solutions/BITS-VPN-Cloudflare/main/KV.json';
export const PRX_BANK_URL =
  'https://raw.githubusercontent.com/Banten-IT-Solutions/BITS-VPN-Cloudflare/main/proxy.txt';
export const DNS_SERVER_ADDRESS = '8.8.8.8';
export const DNS_SERVER_PORT = 53;
export const RELAY_SERVER_UDP = {
  host: 'udp-relay.hobihaus.space',
  port: 7300,
};
export const WS_READY_STATE_OPEN = 1;
export const WS_READY_STATE_CLOSING = 2;
export const CORS_HEADER_OPTIONS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,HEAD,POST,OPTIONS',
  'Access-Control-Max-Age': '86400',
};

// Helper functions
export function getFlagEmoji(isoCode: string): string {
  const codePoints = isoCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

/**
 * Derive a deterministic static UUID v4 from a token string.
 * Used so VLESS links generated by /api/sub always use the same UUID
 * derived from SUB_TOKEN (matching the relay's VLESS auth).
 */
export async function uuidFromToken(token: string): Promise<string> {
  const data = new TextEncoder().encode(token);
  const hash = await crypto.subtle.digest('SHA-256', data);
  const bytes = new Uint8Array(hash).slice(0, 16);

  // Set version (4) and variant (10xx) bits so the result is a valid UUID v4
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;

  const hex = Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

export function shuffleArray<T>(array: T[]): void {
  let currentIndex = array.length;
  while (currentIndex != 0) {
    let randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
}

export function base64ToArrayBuffer(base64Str: string): { earlyData?: ArrayBuffer; error: any } {
  if (!base64Str) {
    return { error: null };
  }
  try {
    base64Str = base64Str.replace(/-/g, '+').replace(/_/g, '/');
    const decode = atob(base64Str);
    const arryBuffer = Uint8Array.from(decode, c => c.charCodeAt(0));
    return { earlyData: arryBuffer.buffer, error: null };
  } catch (error) {
    return { error };
  }
}

export function arrayBufferToHex(buffer: ArrayBuffer): string {
  return [...new Uint8Array(buffer)].map(x => x.toString(16).padStart(2, '0')).join('');
}
