name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

concurrency:
  group: proxy-scan
  cancel-in-progress: false

jobs:
  scanner:
    name: Scan & update proxy list
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          token: ${{ github.token }}

      - name: Use Bun
        uses: oven-sh/setup-bun@v2.2.0

      - name: Start Scan
        run: |
          bun install --frozen-lockfile
          bun run ./helper/proxyip.ts

      - name: Publish Result
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update proxyip"
          git push origin main --force-with-lease